export const FETCH_START = 'FETCH_START';
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const SUCCESS_SIGNIN = 'SUCCESS_SIGNIN';
export const SUCCESS_SIGNOUT = 'SUCCESS_SIGNOUT';